<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Http;
use App\Models\dailyWeatherData;
use App\Models\address;
use App\Models\liveweather;
use Illuminate\Http\Request;

class appContoller extends Controller
{
    function all_locations(){
        $data = address::all();
        return response()->json($data, 200);
    }

    function weatherdata(request $request){
        $data = dailyWeatherData::where('longitude',$request->longitude)->where('latitude',$request->latitude)->latest()->take(7)->get();
        return response()->json($data, 200);
    }

    function liveweather(request $request){
        $data = liveweather::where('longitude',$request->longitude)->where('latitude',$request->latitude)->latest()->take(7)->get();
        return response()->json($data, 200);
    }

    function index(){
        $response = Http::withHeaders([
            'authkey' => '634e0aea96ce7d3961075b2a23446111'
        ])
        ->acceptJson()
        ->get('https://service.weatherimpact.com/api/data/ciat_forecast/weather_sms_text?datetime=latest');

        foreach ($response['Data'][0]['Data'] as $key => $value) { 
            $neededBreakdown = array();
            $breakdown = explode(" ",  $value);

            $value = preg_replace('/[^a-z\s 0-9 -]/', '', strtolower($value));
            $value = preg_split('/\s+/', $value, NULL, PREG_SPLIT_NO_EMPTY);

            $current_val1 = array_search('temperature', $value );
            $current_val2 = array_search('temp', $value);
            
            if (!preg_match('~[0-9]+~', $breakdown[$current_val1 - 1])) {
                $breakdown[$current_val1 - 1] = '0mm';
                $currForcast = 'No rain';
            }else{
                $currForcast = 'Possible Rain';
            }

            if (!preg_match('~[0-9]+~', $breakdown[$current_val2 - 1])) {
                $breakdown[$current_val2 - 1] = '0mm';
                $nextForcast = 'No rain';
            }else{
                $nextForcast = 'Possible Rain';
            }
            array_push(
                $neededBreakdown, 
                $response['GridDefinition']['Latitude'][$key],  
                $response['GridDefinition']['Longitude'][$key],
                date("Y-m-d",strtotime($response['Data'][0]['Date'])),
                rtrim($breakdown[$current_val1 + 1], "."),
                $currForcast,
                $breakdown[$current_val1 - 1],
                $breakdown[$current_val2 + 1],
                $nextForcast,
                rtrim($breakdown[$current_val2 - 1], "."),        
            );
            
            $address = address::where('latitude', $neededBreakdown[0])->where('longitude',$neededBreakdown[1])->first();
            if($address){

                $curl = curl_init();
                // Set some options - we are passing in a useragent too here
                curl_setopt($curl,CURLOPT_TIMEOUT, 3000);
    
                curl_setopt_array($curl, array(
                    CURLOPT_RETURNTRANSFER => 1,
                    CURLOPT_URL => "https://api.openweathermap.org/data/2.5/weather?lat=$neededBreakdown[0]&lon=$neededBreakdown[1]&appid=c2df596100d32243755dd4827069e38b&units=metric",
                    CURLOPT_USERAGENT => 'Codular Sample cURL Request'
                ));
                // Send the request & save response to $resp
                ini_set('max_execution_time', 1800);
                $resp = curl_exec($curl);
                $res = json_decode($resp, true);
    
                // Use parse_url() function to parse the URL
                // and return an associative array which
                // contains its various components
                $url_components = parse_url("https://api.openweathermap.org/data/2.5/weather?lat=$neededBreakdown[0]&lon=$neededBreakdown[1]&appid=c2df596100d32243755dd4827069e38b&units=metric");
                    
                // Use parse_str() function to parse the
                // string passed via URL
                parse_str($url_components['query'], $params);                    
    
                // print_r($res );
                if($res){
                    // dd($res);
                    if(array_key_exists('rain',$res)){
                        $rain = $res['rain']['1h'];
                    }else{
                        $rain = 0.00;
                    }
                $data = liveweather::create([
                    'latitude'=> $res['coord']['lat'],
                    'longitude'=> $res['coord']['lon'],
                    'temperature' => $res['main']['temp'],
                    'humidity' => $res['main']['humidity'],
                    'rain' => $rain,
                    'description' => $res['weather'][0]['description'],
                ]);     
                }else{
                    $data = liveweather::create([
                        'latitude'=> $neededBreakdown[0],
                        'longitude'=> $neededBreakdown[1],
                        'temperature' => 0.0,
                        'humidity' => 0.0,
                        'rain' => 0.0,
                        'description' => 0.0,
                    ]); 

                }
    
                                
                // Close request to clear up some resources
                curl_close($curl);

                $data = dailyWeatherData::create([
                    'address_id'=> $address->id,
                    'latitude' => $neededBreakdown[0],
                    'longitude'=> $neededBreakdown[1],  
                    'date'=> $neededBreakdown[2],
                    'current_temperature'=> $neededBreakdown[3],
                    'current_rain_level'=> $neededBreakdown[5],
                    'current_chance_rain'=> $neededBreakdown[4],
                    'next_temperature'=> $neededBreakdown[6],
                    'next_rain_level'=> $neededBreakdown[8],
                    'next_chance_rain' => $neededBreakdown[7]
                ]);     
            }

            
        }
    }

    function geolocate(){
        ini_set('max_execution_time', 1800);

        $array = [
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=4.8&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.2&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.5&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=5.8&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.2&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.5&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=6.8&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.2&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.5&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=7.8&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.2&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.5&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=8.8&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.2&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.5&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=9.8&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.2&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.5&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=10.8&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.2&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.5&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=11.8&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.2&lon=3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=-5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=-4.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=-4.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=-4.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=-4",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=-3.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=-3.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=-3.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=-3",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=-2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=-2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=-2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=-2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=-1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=-1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=-1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=-1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=-0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=-0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=-0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=0",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=0.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=0.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=0.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=1",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=1.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=1.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=1.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=2.2",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=2.5",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=2.8",
            "https://nominatim.openstreetmap.org/reverse?format=json&lat=12.5&lon=3"
        ];

        foreach ($array as $key => $value) {
            $curl = curl_init();
            // Set some options - we are passing in a useragent too here
            curl_setopt_array($curl, array(
                CURLOPT_RETURNTRANSFER => 1,
                CURLOPT_URL => $value,
                CURLOPT_USERAGENT => 'Codular Sample cURL Request'
            ));
            // Send the request & save response to $resp
            $resp = curl_exec($curl);
            $res = json_decode($resp, true);

            // Use parse_url() function to parse the URL
            // and return an associative array which
            // contains its various components
            $url_components = parse_url($value);
                
            // Use parse_str() function to parse the
            // string passed via URL
            parse_str($url_components['query'], $params);                    

            if(!array_key_exists('error', $res) && $res['address']['country'] == 'Ghana'){
                
                $loc_data = [
                    'location' => $res['display_name'],
                    'longitude' => $params['lon'],
                    'latitude' => $params['lat']
                ];

                $data = address::create($loc_data);
            }
                            
            // Close request to clear up some resources
            curl_close($curl);
            }
    }
    }

